#!/usr/bin/env python3
"""V1L: how much of the HF distortion floor is the RECOVERY SATURATOR? (ablation, 2026-07-19)

CONTEXT. `hf_thd_flatness_check.py` established that V1L's plugin carries a ~2-3% HF THD floor that
is nearly DRIVE-INDEPENDENT (4 kHz: 3.19/2.92/2.25% across D0.65/0.45/0.40) where the pedal's
collapses (2.07/0.72/0.37%). That flatness is REAL, not an estimator artefact -- the swept Farina and
the independent discrete-tone estimator agree to 0.00-0.15 pp on every plugin row.

THE HYPOTHESIS THE FLATNESS POINTS AT. A distortion floor that ignores DRIVE cannot be generated by
the drive stage. V1L's recovery saturator sits DOWNSTREAM of the zener, whose clamping makes its
output level drive-independent -- so a static saturator there produces exactly a drive-independent
floor. It was fitted for Gap F (2026-07-17, gain 0.400 / knee 0.500 / offset 0.100) against LF
anchors only.

L-009: the ablation is proven to CHANGE THE RENDER before any null is read. `--sat-gain 0` was a
silent no-op until 95f2264; do not trust an ablation without this line.

⚠ DO NOT READ THIS AS "DELETE THE SATURATOR". Gap F measured it as a 9x improvement at the LF
anchors (RMS 11.1 dB vs 102.1 disabled). This probe only shows it OVER-contributes at HF. Deleting it
to fix HF would be the fit-one-band-break-another trap this project has hit before.

Run from repo root:
  python3.11 analysis/v1l_sat_hf_ablate.py
"""
import sys,os,tempfile,subprocess
sys.path.insert(0,'analysis')
import numpy as np, analyze as A, noamp_captures as NC
BIN="build/OfflineRender_artefacts/Release/OfflineRender"
orig=NC.load_capture(A.ORIG,warn=False); ref=A.seg_of(orig,"sweep_clean")
def rend(parsed,extra):
    t=tempfile.NamedTemporaryFile(suffix=".wav",delete=False); t.close()
    q=subprocess.run([BIN,A.ORIG,t.name,"--os","8"]+NC.render_args(parsed,extra_args=extra),capture_output=True,text=True)
    if q.returncode!=0: os.unlink(t.name); return None
    x,_=A.align(A.load(t.name),orig); os.unlink(t.name); return x
def tone(sig,hz):
    s=A.seg_of(sig,f"tone_{hz:g}"); return float(A.thd(s,hz)[0])
caps=[(p,q) for p,q in NC.find_captures() if q.get("rev")=="V1L" and A.is_full_length(NC.load_capture(p),orig)]
caps.sort(key=lambda pq:-float(pq[1].get("drive",0)))
print("V1L recovery-saturator ABLATION  (tone THD %, independent estimator)")
print(f"  {'capture':<20} {'f':>6} {'pedal':>7} {'sat ON':>8} {'sat OFF':>8}  {'ON-ped':>7} {'OFF-ped':>8}")
for p,parsed in caps:
    cal,_=A.align(NC.load_capture(p),orig)
    on=rend(parsed,[]); off=rend(parsed,["--sat-gain","0","--sat-knee","0","--sat-offset","0"])
    n=min(len(on),len(off)); d=float(np.max(np.abs(on[:n]-off[:n])))
    lbl=f"V1L D{float(parsed.get('drive',0)):.2f} BL{float(parsed.get('blend',1)):.2f}"
    for hz in (2000,4000):
        pe,o1,o0=tone(cal,hz),tone(on,hz),tone(off,hz)
        print(f"  {lbl:<20} {hz:>6} {pe:>7.2f} {o1:>8.2f} {o0:>8.2f}  {o1-pe:>+7.2f} {o0-pe:>+8.2f}")
    print(f"     [L-009 ablation-live: max|on-off| = {d:.3e}]")
